pc-parts-shop
├── src
│   ├── main.cpp
│   ├── algorithms
│   │   ├── bst.cpp
│   │   ├── bst.h
│   │   ├── merge_sort.cpp
│   │   ├── merge_sort.h
│   │   ├── quick_sort.cpp
│   │   └── quick_sort.h
│   ├── models
│   │   ├── product.h
│   │   ├── cart.h
│   │   └── inventory.h
│   └── utils
│       ├── file_handler.cpp
│       └── file_handler.h
├── data
│   └── inventory.txt
├── Makefile
└── README.md